### ISSUE TITLE
Class DlhGooglemapsModel not found !

### ISSUE THREAD

**Issue by tibisi** [delahaye/dlh_googlemaps#37]
Hi, 

i working on Contao 3.3.2. 
I downloaded your extensions but i've got an error.
Class DlhGooglemapsModel not found.

What did i do ?
1 - Downlaod & install (no pbm)
2 - Create two maps with extensions (no pbm)
3 - Add a map to an article : PROBLEM
     -> Administration no display to let the php error appear

I searched in all files of your extensions but i haven't find any solutions yet. 
Do you have any ideas to resolve this problem ?

Realy thanks 
Romain

**Comment by delahaye** [comment]
There was a problem with the Contao models at this time. Should be gone.
