### ISSUE TITLE
Don't use <section> in Element Template

### ISSUE THREAD

**Issue by fritzmg** [delahaye/dlh_googlemaps#42]
The HTML5 templates of all the element templates (module and content element) use the HTML5 `<section>` tag. However, this doesn't make sense in general. It changes the outline of the document in a way the developer/user doesn't necessarily want.

Take for instance this example structure:

```html
<h1>Page with maps</h1>
  <h2>Some info</h2>
    <p>The info</p>
  <h2>The maps</h2>
    <h3>Map 1</h3>
      <div>The map</div>
    <h3>Map 2</h3>
      <div>The map</div>
```
The outline of this structure is

* Page with maps
  * Some info
  * The maps
    * Map 1
    * Map 2

But since your templates use the `<section>` element, which creates the following basic structure:

```html
<h1>Page with maps</h1>
  <h2>Some info</h2>
    <p>The info</p>
  <h2>The maps</h2>
  <section>
    <h3>Map 1</h3>
      <div>The map</div>
  </section>
  <section>
    <h3>Map 2</h3>
      <div>The map</div>
  </section>
```

The outline would be:

* Page with maps
  * Some info
  * The maps
  * Map 1
  * Map 2

Just to emphasize: `<section>` is not a replacement for `<div>`. `<section>` structures the semantic meaning of the document's content. Think of it like sections in a book, scientific document, thesis etc.

More information:
http://www.smashingmagazine.com/2013/01/18/the-importance-of-sections/
http://html5doctor.com/the-section-element/
http://gsnedders.html5.org/outliner/

**Comment by delahaye** [comment]
You're right, thanks. I'll change it in the next version to a div.
