### ISSUE TITLE
Fehler im Template "dlh_marker.html5" ?

### ISSUE THREAD

**Issue by nkirstein** [delahaye/dlh_googlemaps#44]
Im Template "dlh_marker.html5" werden die Daten aus dem Backend-Feld "Ergänzende Parameter" zweimal abgerufen. Der entsprechende Code-Block
```php
<?php if ($this->element['parameter']) : ?>
    <?php echo $this->element['parameter']; ?>
<?php endif; ?>
```
taucht im Template zweimal auf, nämlich einmal in Zeilen 42-44 und dann noch einmal ganz am Ende in Zeilen 75-77. Der zweite Block kann zu Syntax-Fehlern im generierten JavaScript führen. Wenn man z.B. zwei Marker auf der Googlemap hat und beim ersten als Ergänzenden Parameter `visible:false` (beliebiges Beispiel) eingibt, erzeugt das Template folgenden Code:
```javascript
var gmap1_0_marker = new google.maps.Marker({
    position: new google.maps.LatLng(51.0,23.0), map: gmap1, zIndex: 1, visible:false });
visible:false     var gmap1_1_marker = new google.maps.Marker({
    position: new google.maps.LatLng(51.0,23.0), map: gmap1, zIndex: 1 }); 
```
Das erste `visible:false` ist in den Marker-Optionen und damit an der richtigen Stelle, aber das zweite direkt vor `var gmap1_1_marker = ...` bewirkt einen Syntax-Fehler und die ganze Seite wird nicht angezeigt.

**Comment by delahaye** [comment]
Stimmt absolut und wird entfernt. Merci!
