### ISSUE TITLE
Support the `|async` flag

### ISSUE THREAD

**Issue by katgirl** [delahaye/dlh_googlemaps#45]
Contao 3.4 will support an |async flag for scripts in ```$GLOBALS['TL_JAVASCRIPT']```, see
contao/core#7172
and
contao/core@f3bf1a4

**Comment by delahaye** [comment]
Ist drin.

**Comment by katgirl** [comment]
83206e1e27cf5f0b2c38c51a5056ee93a97be271

**Comment by delahaye** [comment]
Ist wieder raus - machte Probleme.

**Comment by katgirl** [comment]
müsste das nicht auch wie folgt lauten:

```php 
$GLOBALS['TL_JAVASCRIPT'][] = 'http'.(\Environment::get('ssl') ? 's' : '').'://maps.google.com/maps/api/js?v=3.exp&callback=initialize&language='.$arrMap['language'].'&amp;sensor='. ($arrMap['sensor'] ? 'true':'false') . '|async';
```

siehe: https://developers.google.com/maps/documentation/javascript/examples/map-simple-async

**Comment by bastlwastl** [comment]
Ich habe es bei mir so eingefügt: 

`$GLOBALS['TL_JAVASCRIPT'][] = 'http'.(\Environment::get('ssl') ? 's' : '').'://maps.google.com/maps/api/js?key='.$objRootPage->dlh_googlemaps_apikey.'&language='.$arrMap['language'] .' '.async .' '.defer;`

Ist das so machbar? Konnte bis jetzt keine Probleme feststellen.

Gruß Bastian
