### ISSUE TITLE
javascript breaks when marker.title or marker.linkTitle contains double quotes

### ISSUE THREAD

**Issue by cdxOo** [delahaye/dlh_googlemaps#52]
how to reproduce: add a marker that contains double quotes (") -> javascript breaks

how to fix: i quick-fixed it by adding "addSlashes" to the relevant lines in dlh_googlemaps/templates/elements/dlh_marker.html5/xhtml respectively
but dlh_googlemaps/classes/Googlemap.php::getElementData() obviously is the proper place

**Comment by delahaye** [comment]
You're right, thanks. Will be fixed in the next version.
