### ISSUE TITLE
Doesn't work on 3.4.5

### ISSUE THREAD

**Issue by EDsolution** [delahaye/dlh_googlemaps#54]
Hi. I have fresh installation of Contao 3.4.5 and Google Maps Module  2.1.1, but map does not work.
In the source code the map is generated but you can see only gray box. Also no js error.

**Comment by marcobiedermann** [comment]
@EDsolution I got it working on Contao 3.5.14. Maybe you forgot to specify the width and height property in the configuration.

**Comment by delahaye** [comment]
Well, it should work with 3.4.x.
