### ISSUE TITLE
dlh_googlemap_zoom has invalid default value

### ISSUE THREAD

**Issue by fritzmg** [delahaye/dlh_googlemaps#58]
In the DCA of `tl_content`, the [SQL definition](https://github.com/delahaye/dlh_googlemaps/blob/2.1.1/dca/tl_content.php#L65) for the field `dlh_googlemap_zoom` is defined as follows:
```php
"int(10) unsigned NOT NULL default '0'"
```
It's an integer field that cannot be NULL and defaults to zero, if **no** value is given during an `INSERT` operation.

However, the default value [in the DCA](https://github.com/delahaye/dlh_googlemaps/blob/2.1.1/dca/tl_content.php#L63) is defined as follows:
```php
'default' => ''
```
This will lead to a MySQL error, if the MySQL server runs in a _strict mode_, since you cannot insert an empty string into such a field then.

The default value should be defined as follows:
```php
'default' => 0
```

**Comment by delahaye** [comment]
You're right, thanks. I'll set it to an integer value with the next version.
