### ISSUE TITLE
Contao 4.2

### ISSUE THREAD

**Issue by christianromeni** [delahaye/dlh_googlemaps#60]
So I tried to get the Module to run on Contao 4.2.
Up to now, It seems to work, but I get a strange error when creating a Map:

![image](https://cloud.githubusercontent.com/assets/1358040/16309694/f3d7db14-3969-11e6-87f8-da0b4ed893fd.png)

Maybe inputType imageSize is not the right type for this option?

**Comment by christianromeni** [comment]
Hier liegt übrigens der Hund begraben:
https://github.com/contao/core-bundle/commit/8360424a3344c9fbed5798902111833fd94ad9ad

**Comment by delahaye** [comment]
Ich habe noch nichts in Richtung 4.x gemacht, würde mir das daher gerne später ansehen.
