### ISSUE TITLE
[IMPORTANT] Allow to enter API key

### ISSUE THREAD

**Issue by qzminski** [delahaye/dlh_googlemaps#61]
Allow to enter the API key as domains set up after 22nd June require it for Google Maps:

https://googlegeodevelopers.blogspot.com.au/2016/06/building-for-scale-updates-to-google.html

**Comment by fritzmg** [comment]
This needs to be implemented as soon as possible.

The API key should be define-able in the system settings as well as each website root.

**Comment by k-webdesign** [comment]
+1

**Comment by basistom** [comment]
+1

**Comment by poldixd** [comment]
+1

**Comment by delahaye** [comment]
A new Version is coming soon, containing the API key.
