### ISSUE TITLE
API Key - tl_page DCA Verbesserung

### ISSUE THREAD

**Issue by KaiserCh** [delahaye/dlh_googlemaps#62]
Um zukünftige Probleme zu vermeiden, insbesondere bei der Sicherheit, wäre es besser, den EVAL des DCA-Eintrags noch etwas zu erweitern.
'eval' => array('maxlength'=>64, 'rgxp'=>'alnum')
- maxlength, damit die Feldlänge zur Datenbank-Größe passt
- rgxp alnum, damit keiner Schindluder treiben kann. Der Key wird schließlich ungeprüft ausgegeben. Da nicht zu erwarten ist, dass der Google API Key jemals Zeichen wie <>/ enthalten wird, ist alnum eine gute Vorsichtsmaßnahme bei der Eingabe.
- mandatory=false kann hingegen getrost weg. ist eh der Standardwert.

**Comment by delahaye** [comment]
Gute Idee, kommt. Danke!
