### ISSUE TITLE
SVG-Icons bei Markern erlauben

### ISSUE THREAD

**Issue by bezin** [delahaye/dlh_googlemaps#63]
Hallo zusammen,

erst einmal danke für diese Erweiterung. Eine kleine Anmerkung habe ich aber:
Es wäre schön, wenn auch SVGs in der dlh_googlemaps_elements DCA als Icon-Bild erlaubt wären. Ich habe bei Google nichts gefunden, was das nicht gestatten würde :)
https://github.com/delahaye/dlh_googlemaps/blob/master/dca/tl_dlh_googlemaps_elements.php#L291

Viele Grüße
benzin

**Comment by KaiserCh** [comment]
Gibt tatsächlich keinen Grund, warum das nicht gehen sollte. Ich hab das bei 2-3 Projekten auch schon getestet. Am Ende muss nur im DCA von "iconSRC" im eval die Menge der erlaubten Extensions um svg und evtl. noch svgz ergänzt werden.

Als Notbehelf kann man auch einfach folgende Zeile in /system/config/dcaconfig.php schreiben.
$GLOBALS['TL_DCA']['tl_dlh_googlemaps_elements']['fields']['iconSRC']['eval']['extensions'] = 'gif,jpg,jpeg,png,svg,svgz';

**Comment by bezin** [comment]
Ich hatte nun doch Probleme mit einem SVG-Icon in IE11. Ähnliches hier: http://stackoverflow.com/questions/27261346/custom-svg-markers-wont-display-in-ie-11

Ich habe eine zusätzliche Eigenschaft auf dem Marker-Objekt gesetzt, die das Problem zu beheben scheint (siehe auch hier: https://developers.google.com/maps/documentation/javascript/3.exp/reference)
```optimized: false```

**Comment by delahaye** [comment]
Ok, ich hab das DCA mal erweitert. Erweiterte Eigenschaften kann man ja im Template setzen, wenn es nötig ist.
