### ISSUE TITLE
Feature Request: CSS inline statt in Datei frontend.css

### ISSUE THREAD

**Issue by juju2** [delahaye/dlh_googlemaps#65]
Hallo Christian,

vielen Dank für die tolle Erweiterung!

Mir ist gerade aufgefallen, dass Du (nur) auf Seiten, die eine Map einsetzen die globale (compiled) CSS-Datei erweiterst. Das ist nicht optimal für die Performance, da dadurch auf diesen Seiten ein anderes globales CSS eingebunden wird, als auf anderen Seiten - also nicht die eventuell bereits im Cache befindliche CSS-Datei von einem bereits erfolgten anderen Seitenaufruf.

Da es sich in der Datei frontend.css nur um eine Zeile CSS-Code handelt, wäre es toll, das stattdessen als style-tag im Head der Seiten einzusetzen, die eine Map enthalten:
`$GLOBALS['TL_HEAD'][] = '<style>.dlh_googlemap img {max-width:none}.dlh_googlemap .routinglink{white-space:nowrap}</style>';`

Danke und viele Grüße,
juju

**Comment by delahaye** [comment]
Es soll ja änderbar bleiben. Und ich versuche sogar eher, Inline-CSS raus zu bekommen. Du kannst aber im CE "CSS weglassen" aktivieren und es manuell einbauen.
