### ISSUE TITLE
Bug: Clusterer-Image Path is not used

### ISSUE THREAD

**Issue by KaiserCh** [delahaye/dlh_googlemaps#66]
The optional path for the clusterer icon folder has no effect, because of typos in ModuleMap and ContentMap.

The errrors are here:
https://github.com/delahaye/dlh_googlemaps/blob/master/elements/ContentMap.php#L104
https://github.com/delahaye/dlh_googlemaps/blob/master/modules/ModuleMap.php#L110

The problem is: The database field for the Clusterer Image Path is called "cluster**er**Img", while the code checks for clusterImg (missing "er").
Either rename the DB field or fix these 2 lines. If the resulting variable name isn't changed, this wouldn't even break current templates. Just add the missing "er" to the 2nd and 3rd occurrence of $arrMap.

**Comment by Aybee** [comment]
I can confirm this. Here you can see how the new lines should be like https://community.contao.org/de/showthread.php?64437-Clustering-YEAH&p=423176&viewfull=1#post423176

**Comment by delahaye** [comment]
You're right. Will be fixed in the next release. Thanks.
