### ISSUE TITLE
static map is missing key parameter

### ISSUE THREAD

**Issue by fritzmg** [delahaye/dlh_googlemaps#67]
The static map URL for the Frontend and Backend is missing the `key` parameter with the API key (https://developers.google.com/maps/documentation/static-maps/intro).
- https://github.com/delahaye/dlh_googlemaps/blob/2.2.0/classes/Googlemap.php#L107

This is required since June 22nd (for new domains). See also #61

**Comment by prosellen** [comment]
I ran into the same problem and fixed it for me - the result is in pull request #64. It might not be the final (or finest) solution, but it works for me and until there's an official solution, you can try that as a fix.

**Comment by prosellen** [comment]
I ran into the same problem and fixed it for me - the result is in the open pull request #64. It might not be the final (or finest) solution, but it works for me and until there's an official solution, you can try that as a fix.

**Comment by delahaye** [comment]
Thanks, this will be fixedin the next release.

**Comment by Aybee** [comment]
Nur als Hinweis: Zusätzlich zur **Maps JavaScript API** muss auch noch die **Maps Static API** aktiviert werden. Hier die Seite https://console.developers.google.com/apis/library?filter=category:maps zum Aktivieren der Bibliotheken.
