### ISSUE TITLE
Some icons with unclean borders

### ISSUE THREAD

**Issue by Aybee** [delahaye/dlh_googlemaps#68]
Hallo Christian, schau mal bitte auf den Screenshot. Einige dieser Icons haben unsaubere Ränder.

![screen-2016-10-27_21-42-11](https://cloud.githubusercontent.com/assets/1143013/19782703/4bf371fe-9c8f-11e6-91e3-d7ca4b12aa1f.png)

Gruß Andreas

**Comment by delahaye** [comment]
Stimmt schon, aber das sind die vom Clusterer mitgelieferten Dinger, die wollte ich nicht bearbeiten. Trotzdem danke.

**Comment by Aybee** [comment]
Ah, sind die von Google? Hast du mal die Quelle? Ich möchte mich dort mal umschauen.

**Comment by Remo** [comment]
@Aybee Google pflegt das Repo Js Marker Clusterer nicht mehr, die besten Chancen hast du wohl bei uns: https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer

**Comment by Aybee** [comment]
Etwas seltsam, die readme ist schon über ein Jahr alt und auf der Startseite von Maps wird groß mit Cluster geworben. https://developers.google.com/maps/documentation/javascript/?hl=de

Habe es jetzt in eurem Repository nochmal eingestellt.

**Comment by Remo** [comment]
Interessant.. Um so besser wäre es, wenn unser Repo das "offizielle" wird. Mal schauen ob sich bei uns jemand findet der Freude und Fähigkeiten hat Bilder zu verbessern.

**Comment by Aybee** [comment]
Ja, vielen Dank, das wäre ne Verbesserung für alle. Und gutes Gelingen bei dem Versuch dieses Repo als offiziell auszuzeichnen.

**Comment by Remo** [comment]
Merci aber offiziell wird's nicht, das hat Google bereits abgelehnt, aber vielleicht so halb offiziell. Deswegen in Hochkommas ;-)
