### ISSUE TITLE
API key not included in api request

### ISSUE THREAD

**Issue by maettyhawk** [delahaye/dlh_googlemaps#80]
Eventhough I added a Google Maps API key in the settings, the key is not included in the api request. 

`<script src="http://maps.google.com/maps/api/js?key=&language=de"></script>`

I'm running Contao 4.4.3 with dlh_googlemaps 2.3.0 locally (XAMPP on MacOS).

**Comment by maettyhawk** [comment]
Sorry, this refers to the @heimrichhanot version of this extension.

**Comment by delahaye** [comment]
This will be fixed in the next release. Thanks.
