### ISSUE TITLE
Support for snazzy maps

### ISSUE THREAD

**Issue by cgpro** [delahaye/dlh_googlemaps#82]
Feature request :)

It would be nice to have a new field "Snazzy configuration" or "Colour configuration" after the field "Additional declarations", in the map configuration. Maybe with link to the snazzy website in the field hint?

The output could be placed after the center attribute in the file ce_dlh_googlemaps_default.html5 (after line 16).

, styles: [ ... snazzy config ]

Example config:
https://snazzymaps.com/style/25/blue-water

**Comment by delahaye** [comment]
You can already use this. Just paste the given Javascript style array in the config field for additional parameters writing 'styles:' just before it.  E.g.:

<pre>styles:[
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#ff0000"
            }
        ]
    }
]</pre>

**Comment by cgpro** [comment]
Ah, tried it, but without "styles:", thanks! :)
