### ISSUE TITLE
Aktuelle Version ist nicht mehr kompatibel zu Contao 3

### ISSUE THREAD

**Issue by Ynda** [delahaye/dlh_googlemaps#84]
Die Abhängigkeit zu contao-community-alliance/composer-plugin 3.* erzeugt einen Konflikt, das diese Version nicht mehr kompatibel zu Contao 3.* ist

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for delahaye/dlh_googlemaps >=2.3.2.0,<2.4-dev -> satisfiable by delahaye/dlh_googlemaps[2.3.2].
    - delahaye/dlh_googlemaps 2.3.2 requires contao-community-alliance/composer-plugin 3.* -> satisfiable by contao-community-alliance/composer-plugin[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.1.x-dev, 3.0.x-dev].
    - contao-community-alliance/composer-plugin 3.0.0 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.1 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.2 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.3 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.4 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.5 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.6 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.7 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.8 conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.1.x-dev conflicts with contao/core[3.5.29].
    - contao-community-alliance/composer-plugin 3.0.x-dev conflicts with contao/core[3.5.29].
    - Installation request for contao/core 3.5.29 -> satisfiable by contao/core[3.5.29].

**Comment by Webstylerin** [comment]
Habe gerade das gleiche Problem. Nutze Contao 3.5.29.

**Comment by dive13** [comment]
Kann ich bestätigen. Lässt sich unter 3.5.29 per Composer nicht installieren.

**Comment by Ynda** [comment]
Um eine Kompatibilität für Contao3 und 4 zu erhalten ist folgender Eintrag nötig:

## Require the Contao Composer Plugin

There are two different versions of the Plugin currently actively supported.

- Version 2 of the plugin is made for Contao 3. It supports installing Composer packages in TL_ROOT/composer instead of the root directory of your installation.
- Version 3 of the plugin is made for Contao 4. In Contao 4, the vendor folder is located in your installation root, and Contao is just another dependency of your installation.

Make sure to require the correct version of the plugin. If your module does support Contao 3 and Contao 4, the correct require statement looks like this:
`{
    "require": {
        "contao/core-bundle": "~3.5 || ~4.1"
    }
}`

**Comment by csaeum** [comment]
Bitte dringend die Vorschläge von YNDA umsetzen in der aktuellen 3.x geht überhaupt nichts!!!

**Comment by GMTeams** [comment]
Auch unter 3.5.31 keine Installation möglich. Manuellen Weg würde ich gerne vermeiden wenn möglich.

**Comment by delahaye** [comment]
Im kommenden Release ist das behoben/eingebaut. Danke für die Unterstützung!
