### ISSUE TITLE
Add a blank option to the select tl_content.dlh_googlemap_size

### ISSUE THREAD

**Issue by Aybee** [delahaye/dlh_googlemaps#85]
Hallo Christian.

Wenn man seine Google-Map einstellt auf z.B. Proportional 16/9, dann möchte man meistens in den Inhaltselementen die Größe frei lassen, da die Einstellung aus der Map genommen werden soll. Mit dem jetzigen Feld geht dies nicht. Es ist zwar nicht mandatory, aber es fehlt eine leere Option beim Select, sodass es einen Fehler wirft, wenn man dort nichts eintragen möchte.

https://github.com/delahaye/dlh_googlemaps/blob/master/dca/tl_content.php#L66-L75

Evtl. reicht schon ein `includeBlankOption`
```php
...
$GLOBALS['TL_DCA']['tl_content']['fields']['dlh_googlemap_size'] = [
...
  'eval' => ['includeBlankOption' => true, 'nospace' => true, 'helpwizard' => false, 'tl_class' => 'w50 clr'],
...
];
...
```

**Comment by delahaye** [comment]
Kan man machen, kommt im nächsten Release. Danke!

**Comment by Aybee** [comment]
Ich danke auch 🥇
