### ISSUE TITLE
Some imagesize fields needs better options

### ISSUE THREAD

**Issue by Aybee** [delahaye/dlh_googlemaps#86]
Am Beispiel von `infoWindowSize`
https://github.com/delahaye/dlh_googlemaps/blob/master/dca/tl_dlh_googlemaps_elements.php#L402-L411

Wenn man dort einen Wert einträgt und danach wieder den default Zustand herstellen möchte, weiß man eigentlich nicht, was man dort eintragen soll. Normalerweise würde man das Feld dann nicht setzen, aber man **muss** Werte eintragen, da es ansonsten einen Fehler wirft, obwohl es nicht mandatory ist.

Das gilt für so einige `imagesize` Felder. Wenn man diese Felder nicht setzen **muss** und aus diesem Grund auch nicht setzen **möchte**, sollte ein brauchbarer Wert ins Template ausgegeben werden. Das Mindeste wäre ein Hinweis im Hilfetext "0 deaktiviert diese Option".

Ist das default mit `['0', '0', 'px']` richtig gesetzt? Müsste dies nicht `serialize(array(0,0,'box'))` sein? So wie hier? https://github.com/delahaye/dlh_googlemaps/blob/master/dca/tl_content.php#L73

**Comment by delahaye** [comment]
Bevor ich da Arbeit investiere, würde ich das nur in der Beschreibung erledigen. "box" wäre korrekt - serialisieren klappt aber so. Danke.

**Comment by Aybee** [comment]
Ja, ich denke auch ein Hinweis im Tooltip wäre ok.
