### ISSUE TITLE
overviewMapControl seems to be obsolete

### ISSUE THREAD

**Issue by Aybee** [delahaye/dlh_googlemaps#87]
Die Option `overviewMapControl` scheint nichts mehr zu bewirken.
```js
...
overviewMapControl: true,
overviewMapControlOptions: {
  opened: true
}
...
```
Im Netz kann man auch so gut wie nichts mehr darüber finden. Scheint aus V2 zu stammen. Das hier habe ich gefunden
https://code.google.com/archive/p/gmaps-api-v3-overviewmapcontrol/

Ich denke, dass man diese zwei Felder
`tl_dlh_googlemaps.useOverviewMapControl`
`tl_dlh_googlemaps.overviewMapControlOpened`
deswegen entfernen könnte.

**Comment by delahaye** [comment]
Hab ich auch nirgendwo mehr gefunden. Kommt raus. Danke!

**Comment by bezin** [comment]
Es gibt noch ein paar Überbleibsel zu dem Thema, nämlich die Paletten und Selektoren. Ich mache später einen PR :-)
