### ISSUE TITLE
composer-plugin for C3.5 needs to be ~2.4

### ISSUE THREAD

**Issue by Zmyslny** [delahaye/dlh_googlemaps#91]
https://github.com/delahaye/dlh_googlemaps/blob/68e92cfbcf4b0cd2850e673e8fcc3d5df8ad5d63/composer.json#L22

Could U update this to:
"contao-community-alliance/composer-plugin": "~2.4 || ~3.0"
so it will install nicely, using composer, on most Contao 3.5.x instalations...

**Comment by Zmyslny** [comment]
the same issue for dlh_geocode...

**Comment by delahaye** [comment]
Will be fixed in the coming release. Thanks!
