### ISSUE TITLE
Kein https: mit aktiviertem Routenplaner

### ISSUE THREAD

**Issue by 31er** [delahaye/dlh_googlemaps#92]
Habe meine Contao 3.5.31 Installation auf SSL umgestellt, bekomme jedoch bei der Validierung Hinweise, dass Teile von Google Maps nicht korrekt eingebunden sind, weil ein http: Link verwendet wird.

Der http-Link befindet sich in Markierungen mit aktiviertem Routing (Routenplaner verwenden).
` ... form action="http://maps.google.com/maps" method="get" ... `

Die Map selber wir korrekt mit https eingebunden.

**Comment by 31er** [comment]
Sorry, ganz vergessen.
Problem liegt im Template "dlh_marker.html5".

**Comment by delahaye** [comment]
Dann hast Du wohl ein altes Template. Darin stehen alle Links zu Google als https://.
