### ISSUE TITLE
Usage as module

### ISSUE THREAD

**Issue by NicolasGoerlach** [delahaye/dlh_googlemaps#93]
- map_legend translation is missing
- map size "proportional" is missing

![bildschirmfoto 2018-01-17 um 11 06 26](https://user-images.githubusercontent.com/8327905/35037067-9a20e16c-fb76-11e7-957b-caf04fc37a1b.jpg)

**Comment by delahaye** [comment]
Stimmt, fehlt. Im kommenden Release ist das behoben/eingebaut. Danke für die Unterstützung!
