### ISSUE TITLE
SQL für Templatenamen auf 64 setzen

### ISSUE THREAD

**Issue by zonky2** [delahaye/dlh_googlemaps#97]
Contao Core:
https://github.com/contao/core/blob/3.5/system/modules/core/dca/tl_module.php#L244-L261
wurde geändert in https://github.com/contao/core/commit/20b552f6553d6351465a65a2614a8eb570140092

dlh_googlemaps:
https://github.com/delahaye/dlh_googlemaps/blob/master/dca/tl_module.php#L52

**Comment by delahaye** [comment]
Im kommenden Release ist das behoben/eingebaut. Danke für die Unterstützung!
