### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by operatorone** [delahaye/dlh_googlemaps#99]
Nach der Installation bleiben diese Einträge im Datenbank aktualisieren-Dialog bestehen. Egal was man macht. Erweiterung funktioniert trotzdem einwandfrei. 

```
ALTER TABLE tl_dlh_geocode CHANGE longitude longitude DOUBLE PRECISION DEFAULT '0.000000' NOT NULL

  | ALTER TABLE tl_dlh_geocode CHANGE latitude latitude DOUBLE PRECISION DEFAULT '0.000000' NOT NULL
```

Contao 4.4.17 
heimrichhannot/dlh_googlemaps Version 2.3.8

**Comment by delahaye** [comment]
Das betrifft eine geforkte Version.
